import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { poppins } from "./fonts/app.font";
import { NotificationProvider } from './components/providers/NotificationProvider';
import { ReactQueryProvider } from './components/providers/reactquery.provider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AntdRegistry>
        <NotificationProvider>
          <ReactQueryProvider>
            {children}
            </ReactQueryProvider>

            </NotificationProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
